Issue #97 : Create sequential divider with repeated subtraction
etf-unibl/pds-2023 pull request #107
Opened 2023-12-25 20:50 UTC by RadonicA

- Added sequential_divider.vhd
- Added .sdc file

2023-12-28 08:32 UTC, lukavidic requested changes
Dizajn je urađen kako treba, poštuje zahtjevanu RT metodologiju izrade, ispunjava koding standard, dokumentovan odlično sa Doxygen komentarima. Funkcionalno je potpuno ispravan što potrvđuje samoprovjerljivi testbench.
Jedina zamjerka koju imam je vremenska analiza koja mi ne prolazi, iz izuzetno čudnog razloga - narušavanja hold vremena. Bilo bi dobro još to popraviti pa bi to bilo to 😄 
![slack](https://github.com/etf-unibl/pds-2023/assets/117661784/a5a9787a-80db-40f3-a18f-59157b2af683)

2023-12-28 10:01 UTC, RadonicA commented
@lukavidic Kolega, hvala Vam na sugestijama.

2023-12-28 10:34 UTC, knezicm approved these changes

2023-12-28 12:25 UTC, milos991 approved these changes

2023-12-28 12:41 UTC, lukavidic approved these changes

2023-12-29 10:21 UTC, RadonicA commented
@knezicm Profesore, u prethodnom commit-u sam greškom izbrisala mapirane portove, pa sam iz tog razloga napravila izmjene.

2023-12-29 10:25 UTC, milos991 approved these changes

2023-12-29 10:38 UTC, lukavidic approved these changes

2023-12-29 19:12 UTC, knezicm approved these changes

2023-12-29 19:12 UTC, merged