Issue #9 : Sequential add-and-shift multiplier
etf-unibl/pds-2023 pull request #110
Opened 2023-12-28 22:40 UTC by dleg98

- Added VHDL file
- Added SDC file

2023-12-29 22:25 UTC, knezicm requested changes
Nije dobar naslov PR-a.

2023-12-29 22:30 UTC, knezicm commented
> Nije dobar naslov PR-a.

Issue No. sigurno nije #9.

2024-01-11 14:56 UTC, NikolaBabic1213 commented
Dizajn poštuje RT metodologiju te radi korektno što je i potvrđeno testbench-om. Koding standard ispoštovan, ne prijavljuje greške, osim one vezane za doxygen dokumentaciju, koja je takođe adekvatna. SDC fajl je dobro napisan te vremenska analiza prolazi bez bilo kakvih grešaka. Pin assignment je uredan. Nemam nikakvih zamjerki za realizaciju ovog zadatka, osim sitnice, a to je da se zadatak mora prebaciti u tab "In Review". Mimo toga, sve je korektno odrađeno.

2024-01-11 14:57 UTC, NikolaBabic1213 approved these changes
Dizajn poštuje RT metodologiju te radi korektno što je i potvrđeno testbench-om. Koding standard ispoštovan, ne prijavljuje greške, osim one vezane za doxygen dokumentaciju, koja je takođe adekvatna. SDC fajl je dobro napisan te vremenska analiza prolazi bez bilo kakvih grešaka. Pin assignment je uredan. Nemam nikakvih zamjerki za realizaciju ovog zadatka, osim sitnice, a to je da se zadatak mora prebaciti u tab "In Review". Mimo toga, sve je korektno odrađeno.

2024-01-17 09:42 UTC, milos991 approved these changes

2024-01-29 08:59 UTC, knezicm approved these changes

2024-01-29 08:59 UTC, merged