Issue #5 : Added test files
etf-unibl/pds-2023 pull request #26
Opened 2023-10-26 17:59 UTC by NikolaBabic1213

- Created folder 5
- Added test file test.vhdl

2023-10-31 20:27 UTC, knezicm commented
Issue number nije 5 vec 25, prema tome, ne mogu da prihvatim ovako predano rjesenje. Nesto ocigledno niste dobro razumjeli u procesu predaje rjesenja.

2023-10-31 20:29 UTC, knezicm requested changes
Popravite naziv foldera i commit message u PR tako da odgovara broju issue-a Vaseg zadatka i ponovo predajte rjesenje koje ce da sadrzi samo jedan fajl unutar foldera.

2023-10-31 20:29 UTC, knezicm commented on assignments/5/test.vhd
Samo jedan fajl treba da se nalazi u folderu. Koristite `vhd` ekstenziju.

2023-11-01 19:29 UTC, NikolaBabic1213 commented
> Issue number nije 5 vec 25, prema tome, ne mogu da prihvatim ovako predano rjesenje. Nesto ocigledno niste dobro razumjeli u procesu predaje rjesenja.

Ispravih Issue number i ime foldera. Jel sad sve u redu?

2023-11-01 19:40 UTC, closed without merging