27 create simple alu circuit
etf-unibl/pds-2023 pull request #50
Opened 2023-11-03 09:38 UTC by dleg98

- Create a simple ALU vhd file
- Create a scd file

2023-11-03 10:03 UTC, dleg98 commented
Profesore, dobila sam grešku i pogledala logove, mislim da je isti slučaj kao i kod kolege Nemanje.

2023-11-03 10:06 UTC, knezicm commented
> Profesore, dobila sam grešku i pogledala logove, mislim da je isti slučaj kao i kod kolege Nemanje.

Nije ista greska. KOd Vas je problem pri kompajliranju, nesto ne valja oko case naredbe.

2023-11-04 15:45 UTC, knezicm requested changes
U ovom zadatku nije dozvoljeno koristiti proces i **case-when** sekvencijalnu naredbu. U tekstu se eksplicitno traži da se dizajn realizuje korišćenjem **konkurentnih naredbi** (dopušteno je korišćenje biblioteke za realizaciju aritmetičkih operacija za sabiranje/oduzimanje, međutim, korišćenje biblioteka funkcija za operacije pomjeranja sadržaja **nije dozvoljeno**).

2023-11-05 13:46 UTC, knezicm commented
Čini se da nešto nije u redu sa interfejsom dizajna.

![image](https://github.com/etf-unibl/pds-2023/assets/28368588/c81c5a9c-b4c6-462b-8702-9d81f4de22ef)

@milos991 Možeš li provjeriti da li je u testu ispravno definisan interfejs, pošto mi se čini da je kod koleginice entitet napisan kako treba?

2023-11-06 07:25 UTC, milos991 commented
Bice riješeno u toku dana.

2023-11-06 18:57 UTC, milos991 requested changes
Riješio sam problem sa nazivima portova. Možete pogledati log, nisu dobro implementirane operacije šiftanja.

2023-11-07 20:24 UTC, knezicm approved these changes

2023-11-17 19:06 UTC, milos991 approved these changes

2023-11-18 19:38 UTC, merged