Issue #55 : Eight bit divider
etf-unibl/pds-2023 pull request #71
Opened 2023-11-24 11:52 UTC by dleg98

- Created VHD file  
- Created testbench file 
- Added SDC file

2023-11-26 10:52 UTC, knezicm commented
Iako implementacija ovdje očigledno nije korektna, ostaje pitanje interpretacije dijeljenja nulom. @milos991 Da li možeš pogledati kako smo odlučili da razriješimo taj slučaj, pa da ga ugradim u tekst zadatka?

2023-12-04 21:25 UTC, dleg98 commented
[simulation-log.txt.txt](https://github.com/etf-unibl/pds-2023/files/13551440/simulation-log.txt.txt)

2023-12-05 09:07 UTC, knezicm requested changes

2023-12-05 09:07 UTC, knezicm commented on assignments/55/eight_bit_divider.vhd
> +-----------------------------------------------------------------------------
Zašto je header ponovljen dva puta? Izbaciti duplirani header.

2023-12-06 18:01 UTC, knezicm approved these changes

2023-12-06 18:02 UTC, merged