Issue #73: Create alternating priority arbiter circuit
etf-unibl/pds-2023 pull request #83
Opened 2023-11-27 12:10 UTC by lukavidic

- Added arbiter design file
- Added testbench file in subfolder testing
- Added .sdc file with mapped pin locations

2023-11-27 12:20 UTC, lukavidic commented
@knezicm 
Gledajuci logove mislim da greška kod verif nije do mene, izgleda kao da nema testa za ovaj zadatak, ali opet nisam siguran. Pa ako možete kada stignete da pogledate u čemu je problem.

2023-11-27 19:13 UTC, knezicm commented
> @knezicm Gledajuci logove mislim da greška kod verif nije do mene, izgleda kao da nema testa za ovaj zadatak, ali opet nisam siguran. Pa ako možete kada stignete da pogledate u čemu je problem.

Test još uvijek nije spreman.  @milos991 mi je obećao da će biti tokom sedmice. :)

2023-12-01 21:16 UTC, knezicm requested changes

2023-12-01 21:16 UTC, knezicm commented on assignments/73/arbiter.vhd
> +--! @details Architecture written using Moore FSM theory with state register logic, next state logic and Moore output logic in separate processes.
![image](https://github.com/etf-unibl/pds-2023/assets/28368588/aad08ba4-52e1-4928-a639-d64f53024f4d)

Možemo tolerisati devijaciju u odnosu na coding standard vezano za doxygen komentare (`[Comments] space required after comment`), ali sve ostalo je potrebno ispoštovati.

2023-12-01 21:31 UTC, lukavidic commented on assignments/73/arbiter.vhd
> +--! @details Architecture written using Moore FSM theory with state register logic, next state logic and Moore output logic in separate processes.
Sada je popravljeno, trebalo bi da su ostale greske lintera samo vezano za testbench fajl i ove koje ste naveli.

2023-12-02 12:11 UTC, milos991 approved these changes

2023-12-05 09:03 UTC, merged