Issue #74 : Create modified memory controller (first method)
etf-unibl/pds-2023 pull request #91
Opened 2023-12-05 19:30 UTC by AnjaDj

Added entity .vhd file
Added testbench .vhd file
Added .sdc file

2023-12-11 08:25 UTC, milos991 approved these changes

2023-12-28 10:04 UTC, knezicm requested changes

2023-12-28 10:04 UTC, knezicm commented on assignments/74/mem_ctrl.vhd
> +--! @brief Architecture definition of the mem_ctrl
Neophodno je takođe opisati kako je arhitektura realizovana (korišćena je FSM metodologija sa tim i tim brojem stanja, koji tip mašine stanja i tako dalje).

2023-12-29 14:01 UTC, AnjaDj commented
@knezicm Profesore, da li su ove izmjene dovoljne ili je potrebno još nešto?

2023-12-29 18:45 UTC, knezicm approved these changes

2023-12-29 18:45 UTC, merged