Issue #81 : Preamble generator
etf-unibl/pds-2023 pull request #93
Opened 2023-12-17 18:29 UTC by dleg98

- Added Preamble generator vhd file
- Added SDC file
- Added testbech file

2023-12-28 10:19 UTC, knezicm requested changes
Popravite ovo što je navedeno u komentarima i riješite ovo što je linter prijavio, jer tolerišemo samo onaj razmak poslije komentara, a ovdje linter prijavljuje i indentation.

![image](https://github.com/etf-unibl/pds-2023/assets/28368588/a49ba4c1-8fc0-42b7-a0df-eb39bb93faaf)

2023-12-28 10:19 UTC, knezicm commented on assignments/81/preamble_generator.vhd
> +--! @brief Architecture defining the preamble generator
Arhitektura implementira/realizuje funkcionalnost, a ne definiše. Takođe, napišite ukratko kako je arhitektura koncipirana (koristi FSM metodologiju sa toliko stanja, ukratko kako se realizuje, npr. kroz tri procesa kojima se realizuje registarska logika, next-state logika i output logika). Takođe, bitno je da u opisu stoji koji je tip  mašine stanja korišćen.

2023-12-28 12:21 UTC, milos991 approved these changes

2024-01-29 09:09 UTC, knezicm approved these changes

2024-01-29 09:09 UTC, merged