Issue #80: Create dual edge detector circuit using moore fsm
etf-unibl/pds-2023 pull request #94
Opened 2023-12-17 22:03 UTC by bsav98

- Added entity file
- Added testbench file
- Added .sdc file

2023-12-28 10:27 UTC, knezicm requested changes
Popravite ovo navedeno u komentarima. Takođe, provjera linterom ne prolazi. Koliko vidim, koristite blok komentare a to nije dozvoljeno coding standardom. Takođe, tolerišemo samo odstupanje koje se odnosi na razmak kod komentara (zbog _doxygen_ dokumentacije). Ostale stvari iz coding standarda moraju da budu zadovoljene.

2023-12-28 10:27 UTC, knezicm commented on assignments/80/dual_edge_detector.vhd
> + * @brief Architecture for dual_edge_detector module
Potrebno je malo opisati arhitekturu: kako je koncipirana (FSM metodologija), koja mašina stanja je implementirana, koliko ima stanja itd.

2023-12-28 12:22 UTC, milos991 approved these changes

2023-12-29 18:51 UTC, knezicm requested changes
Ne vidim testbench fajl, a i rezultate lokalne simulacije trebate priloziti u okviru zadatka.

2023-12-29 19:33 UTC, bsav98 commented
[pds_log.txt](https://github.com/etf-unibl/pds-2023/files/13795722/pds_log.txt)

2024-01-29 09:07 UTC, knezicm approved these changes

2024-01-29 09:07 UTC, merged